name: Build and Publish image to Docker hub

on:
  [workflow_dispatch]

jobs:

  build:

    runs-on: ubuntu-22.04
    
    steps:
    - name: Set dynamic TAG variable
      id: set_tag
      run: echo "TAG=$(date +%s)" >> $GITHUB_ENV
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build ./UserService --file ./UserService/Dockerfile -t lamersbart/pridr-userservice:$TAG
    - name: push image to hub
      run: docker push lamersbart/pridr-userservice:$TAG
