name: test

on:
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-22.04

    permissions:
      actions: write
      contents: read

    steps:
      - name: Trigger Integration Tests Workflow
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $PAT_TOKEN" \
            https://api.github.com/repos/LamersBart/Pridr-IntergrationTest/actions/workflows/137682142/dispatches \
            -d '{"ref":"main"}'

      - name: Wait for Integration Test Completion
        uses: actions/github-script@v6
        with:
          script: |
            const result = await github.rest.actions.listWorkflowRuns({
              owner: 'LamersBart',
              repo: 'Pridr-IntergrationTest',
              workflow_id: 137682142,
              branch: 'main',
              per_page: 1,
              status: 'completed'
            });

            const run = result.data.workflow_runs[0];
            if (!run || run.conclusion !== 'success') {
              core.setFailed('Integration tests failed!');
            } else {
              console.log('Integration tests succeeded!');
            }
