name: test

on:
  workflow_dispatch:

jobs:
  integration-tests:
    runs-on: ubuntu-22.04

    permissions:
      actions: write
      contents: read

    steps:
      - name: Trigger Integration Tests Workflow
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $PAT_TOKEN" \
            https://api.github.com/repos/LamersBart/Pridr-IntergrationTest/actions/workflows/137682142/dispatches \
            -d '{"ref":"main"}'

      - name: Wait for Integration Test Completion
        uses: actions/github-script@v6
        with:
          script: |
            const owner = 'LamersBart';
            const repo = 'Pridr-IntergrationTest';
            const workflowId = 137682142;
            const branch = 'main';
            const perPage = 1;

            console.log("Wachten op voltooiing van de workflow...");
            let isCompleted = false;
            let run;
            let attempts = 0;
            const maxAttempts = 30; // Maximaal aantal pogingen om te wachten
            const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

            while (!isCompleted && attempts < maxAttempts) {
              const result = await github.rest.actions.listWorkflowRuns({
                owner,
                repo,
                workflow_id: workflowId,
                branch,
                per_page: perPage,
                status: 'in_progress',
              });

              run = result.data.workflow_runs[0];
              if (run && run.status === 'completed') {
                isCompleted = true;
              } else {
                console.log(`Workflow nog niet voltooid. Wacht 10 seconden... (Poging ${attempts + 1}/${maxAttempts})`);
                await delay(10000); // Wacht 10 seconden
                attempts++;
              }
            }

            if (!run || run.status !== 'completed') {
              core.setFailed('Workflow is niet voltooid binnen de maximale wachttijd.');
            } else if (run.conclusion !== 'success') {
              core.setFailed(`Workflow is voltooid maar mislukt: ${run.conclusion}`);
            } else {
              console.log('Workflow succesvol voltooid!');
            }
